#!/bin/bash
#SBATCH -J GEOM_FUNCTIONAL_qc # job name
#SBATCH -N 1
#SBATCH -o GEOM_FUNCTIONAL_qc.o%j # output and error file name (%j expands to jobID)
#SBATCH -t 48:00:00 # run time (hh:mm:ss)
#SBATCH -q regular
#SBATCH -C haswell
#SBATCH --mem 96G
date

module purge
module load qchem

rundir=/$SCRATCH/"$SLURM_JOB_USER"_"$SLURM_JOB_ID"
/bin/rm -rf $rundir
/bin/mkdir -p $rundir

cp sp.txt $rundir
cp test.in $rundir
cd $rundir

srun qchem -np 16 GEOM_FUNCTIONAL.in GEOM_FUNCTIONAL.out

cp -auv * $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR/
rm -rf $rundir

date

echo Done!
