#!/bin/bash
#SBATCH  -J NAME_clus           # Job Name
#SBATCH  -o NAME_clus.o%j       # Output and error file name (%j expands to jobID)
#SBATCH  -N 1                   # Number of nodes, ensure that all cores are on one machine
#SBATCH  -n 20           		# Total number of mpi tasks requested
#SBATCH  -p short               # Partition short <= 4 hours
#SBATCH  -t 4:00:00	            # Run time (hh:mm:ss) - 2 hours

module purge
module load gromacs
module load vmd

dir=$SLURM_SUBMIT_DIR
    
# align the structures & save as trr
for j in `seq 3`; do
    vmd -dispdev text -e $dir/../bak/align.tcl -args zone${j}

    echo 0 > inp
    echo 0 >> inp
    gmx_mpi cluster -f zone${j}.trr -s zone${j}_ref.pdb \
                    -nofit -nopbc -method gromos \
                    -dist rmsd-dist-zone${j}.xvg \
                    -cl clusters-zone${j}.pdb \
                    -o rmsd-clust-zone${j}.xpm \
                    -g cluster-zone${j}.log < inp
    rm -f inp

    awk '{print $3}' cluster-zone${j}.log | sort -n -u | sed 1d | sort -n -u > cluster_pop-zone${j}.dat
    sum=`awk '{sum+=$1} END {print sum}' cluster_pop-zone${j}.dat`
    awk '{print $1/'$sum'}' cluster_pop-zone${j}.dat > cluster_percent-zone${j}.dat
    
done


echo Done!
