#!/bin/bash
#SBATCH  -J NAME_ZONE           # Job Name
#SBATCH  -o NAME_ZONE.o%j       # Output and error file name (%j expands to jobID)
#SBATCH  -N 1                   # Number of nodes, ensure that all cores are on one machine
#SBATCH  -n 1           		# Total number of mpi tasks requested
#SBATCH  -p short               # Partition short <= 4 hours
#SBATCH  -t 4:00:00	            # Run time (hh:mm:ss) - 2 hours

module purge
module load vmd

dir=$SLURM_SUBMIT_DIR
    
vmd -parm7 NAME_new.prmtop -crdbox NAME_new.mdcrd -e $dir/../bak/backtrack_crd.tcl -args ZONE

echo Done!
