#!/bin/bash
#SBATCH  -J NAME_ext2_prd            # Job Name
#SBATCH  -o NAME_ext2_prd.o%j        # Output and error file name (%j expands to jobID)
#SBATCH  -N 2                   # Number of nodes, ensure that all cores are on one machine
#SBATCH  -n 20           		# Total number of mpi tasks requested
#SBATCH  -p medium              # Partition short <= 4 hours
#SBATCH  -t 20:00:00	        # Run time (hh:mm:ss) - 2 hours

module purge
module load amber
rundir=/scratch/"$SLURM_JOB_USER"_"$SLURM_JOB_ID"
/bin/rm -rf $rundir
/bin/mkdir -p $rundir
cp * $rundir
cd $rundir

sander=/share/apps/amber12/bin/sander.MPI
    
date

  mpirun sander.MPI                 \
  -O -i prd_ext.in -o NAME_ext2.out  \
  -p NAME_new.prmtop -c NAME_ext.rst     \
  -r NAME_ext2.rst -x NAME_ext2.mdcrd     

cp -auv *  $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR/
rm -rf $rundir/

date
echo Done!
